version: "3.3"
services:
  react:
    image: node:12.17.0
    working_dir: /code
    volumes:
      - ./react_app:/code
    ports:
      - 3000:3000
    environment: 
      - NODE_ENV=production
    container_name: react_app
